lib/sneakers23_web/router.ex
defmodule Sneakers23Web.Router do
  use Sneakers23Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, html: {Sneakers23Web.Layouts, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Sneakers23Web.Plugs.CartIdPlug
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :admin do
    plug :auth
    plug :put_layout, html: {Sneakers23Web.Layouts, :admin}
  end

  defp auth(conn, _opts) do
    username = System.get_env("AUTH_USERNAME") || "admin"
    password = System.get_env("AUTH_PASSWORD") || "password"
    Plug.BasicAuth.basic_auth(conn, username: username, password: password)
  end

  scope "/", Sneakers23Web do
    pipe_through :browser

    # get "/", PageController, :home
    get "/", ProductController, :index

    get "/checkout", CheckoutController, :show
    post "/checkout", CheckoutController, :purchase
    get "/checkout/complete", CheckoutController, :success

    live "/drops", ProductLive
  end

  scope "/admin", Sneakers23Web.Admin do
    pipe_through [:browser, :admin]
    get "/", DashboardController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", Sneakers23Web do
  #   pipe_through :api
  # end

  # Enable LiveDashboard and Swoosh mailbox preview in development
  if Application.compile_env(:sneakers23, :dev_routes) do
    # If you want to use the LiveDashboard in production, you should put
    # it behind authentication and allow only admins to access it.
    # If your application does not have an admins-only section yet,
    # you can use Plug.BasicAuth to set up some basic authentication
    # as long as you are also using SSL (which you should anyway).
    import Phoenix.LiveDashboard.Router

    scope "/dev" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: Sneakers23Web.Telemetry
      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/sneakers23/checkout.ex
defmodule Sneakers23.Checkout do
  alias __MODULE__.ShoppingCart

  defdelegate add_item_to_cart(cart, item), to: ShoppingCart, as: :add_item

  defdelegate cart_item_ids(cart), to: ShoppingCart, as: :item_ids

  defdelegate export_cart(cart), to: ShoppingCart, as: :serialize

  defdelegate remove_item_from_cart(cart, item), to: ShoppingCart, as: :remove_item

  def restore_cart(nil), do: ShoppingCart.new()

  def restore_cart(serialized) do
    case ShoppingCart.deserialize(serialized) do
      {:ok, cart} -> cart
      {:error, _} -> restore_cart(nil)
    end
  end

  # for browser cookie save temp topic ex: "cart:123"
  @cart_id_length 64
  def generate_cart_id() do
    :crypto.strong_rand_bytes(@cart_id_length)
    |> Base.encode64()
    |> binary_part(0, @cart_id_length)
  end

  def purchase_cart(cart, opts \\ []) do
    Sneakers23.Repo.transaction(fn ->
      Enum.each(cart_item_ids(cart), fn id ->
        case Sneakers23.Checkout.SingleItem.sell_item(id, opts) do
          :ok ->
            :ok

          _ ->
            Sneakers23.Repo.rollback(:purchase_failed)
        end
      end)

      :purchase_complete
    end)
  end
end

lib/sneakers23/checkout/shopping_cart.ex
defmodule Sneakers23.Checkout.ShoppingCart do
  defstruct items: []
  def new(), do: %__MODULE__{}

  def add_item(cart = %{items: items}, id) when is_integer(id) do
    if id in items do
      {:error, :duplicate_item}
    else
      {:ok, %{cart | items: [id | items]}}
    end
  end

  def remove_item(cart = %{items: items}, id) when is_integer(id) do
    if id in items do
      {:ok, %{cart | items: List.delete(items, id)}}
    else
      {:error, :not_found}
    end
  end

  def item_ids(%{items: items}), do: items

  @base Sneakers23Web.Endpoint
  @salt "shopping cart serialization"
  @max_age 86400 * 7

  def serialize(cart = %__MODULE__{}) do
    {:ok, Phoenix.Token.sign(@base, @salt, cart, max_age: @max_age)}
  end

  def deserialize(serialized) do
    case Phoenix.Token.verify(@base, @salt, serialized, max_age: @max_age) do
      {:ok, data} ->
        items = Map.get(data, :items, [])
        {:ok, %__MODULE__{items: items}}

      e = {:error, _reason} ->
        e
    end
  end
end

lib/sneakers23/checkout/single_item.ex
defmodule Sneakers23.Checkout.SingleItem do
  alias Sneakers23.Inventory
  alias Inventory.Store

  def sell_item(item_id, opts \\ []) do
    inventory_opts = Keyword.get(opts, :inventory_opts, [])

    with {:db, :ok} <- {:db, Store.reduce_availability(item_id)} do
      Task.start_link(fn -> Inventory.item_sold!(item_id, inventory_opts) end)
      :ok
    else
      {:db, e = {:error, _}} ->
        e
    end
  end
end

lib/sneakers23_web/controllers/checkout/checkout_controller.ex
defmodule Sneakers23Web.CheckoutController do
  use Sneakers23Web, :controller

  def show(conn, %{"serialized_cart" => serialized_cart}) do
    cart = cart(serialized_cart)
    %{items: items} = Sneakers23Web.CartHTML.cart_to_map(cart)

    case items do
      [] ->
        render(conn, :empty)

      items ->
        conn
        |> assign(:items, items)
        |> assign(:serialized_cart, serialized_cart)
        |> assign(:cant_purchase?, cant_purchase?(items))
        |> render(:show)
    end
  end

  def show(conn, _params), do: redirect(conn, to: ~p"/")

  def purchase(conn, params) do
    with serialized_cart <- Map.get(params, "serialized_cart"),
         cart <- cart(serialized_cart),
         %{items: items} when items != [] <- Sneakers23Web.CartHTML.cart_to_map(cart),
         {:availability, false} <- {:availability, has_out_of_stock_items?(items)},
         {:released, false} <- {:released, has_unreleased_items?(items)},
         {:purchase, {:ok, _}} <- {:purchase, Sneakers23.Checkout.purchase_cart(cart)} do
      redirect(conn, to: ~p"/checkout/complete")
    else
      %{items: []} ->
        conn
        |> put_flash(:error, "Your cart is empty")
        |> redirect(to: ~p"/checkout?#{params}")

      {:availability, true} ->
        conn
        |> put_flash(:error, "Your cart has out-of-stock shoes")
        |> redirect(to: ~p"/checkout?#{params}")

      {:released, true} ->
        conn
        |> put_flash(:error, "Your cart has unreleased shoes")
        |> redirect(to: ~p"/checkout?#{params}")

      {:purchase, _} ->
        conn
        |> put_flash(:error, "Your purchase could not be completed")
        |> redirect(to: ~p"/checkout?#{params}")
    end
  end

  def success(conn, _params) do
    conn
    |> render(:success)
  end

  defp cart(serialized) do
    Sneakers23.Checkout.restore_cart(serialized)
  end

  defp cant_purchase?(items), do: has_out_of_stock_items?(items) || has_unreleased_items?(items)
  defp has_out_of_stock_items?(items), do: Enum.any?(items, & &1.out_of_stock)
  defp has_unreleased_items?(items), do: Enum.any?(items, &(!&1.released))
end

lib/sneakers23_web/controllers/checkout/checkout_html.ex
defmodule Sneakers23Web.CheckoutHTML do
  use Sneakers23Web, :html

  embed_templates "checkout_html/*"
end

lib/sneakers23_web/controllers/checkout/checkout_html/empty.html.eex
<div class="checkout-container">
  <div>No items to checkout!</div>
</div>

lib/sneakers23_web/controllers/checkout/checkout_html/show.html.heex
<div class="checkout-container">
  <h2>Your Cart</h2>


  <%= if Phoenix.Flash.get(@flash, :error) do %>
    <p class="alert alert-danger" role="alert">Sorry, { Phoenix.Flash.get(@flash, :error) }.</p>
  <% end %>

  <div>
    <%= for item <- @items do %>
      <div class="product-listing" data-item-id={item.id}>
        <div class="product-listing__image-wrap checkout__image-wrap">
          <img src={item.main_image_url} />
        </div>

        <div class="product-listing__details">
          <h4 class="product-listing__detail-header"><%= item.name %></h4>

          <div>by { item.brand }</div>
          <div><%= item.color %></div>
          <div>$<%= item.price_usd %></div>
          <div>Size <%= item.size %></div>

          <%= if item.out_of_stock do %>
            <strong>Sorry, this shoe is sold out</strong>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

  <h2>Payment Information</h2>

  <p>Normally, you'd enter a bunch of information. But this is a book example, so just click the button below.</p>

  <form  action={~p"/checkout"} method="POST">
    <input type="hidden" name={"serialized_cart"} value={@serialized_cart} />
    <input type="hidden" name={"_csrf_token"} value={get_csrf_token()} />
    <button :if={@cant_purchase?} class="purchase-button" type="submit" disabled >SOME ITEMS NOT AVAILABLE</button>
    <button :if={!@cant_purchase?} class="purchase-button" type="submit">PURCHASE</button>
  </form>
  <%!-- <%= form_for @conn, Routes.checkout_path(@conn, :purchase), fn f -> %>
    <%= hidden_input f, :serialized_cart, value: @serialized_cart %>

    <%= if @cant_purchase? do %>
      <%= submit "SOME ITEMS NOT AVAILABLE", class: "purchase-button", disabled: true %>
    <% else %>
      <%= submit "PURCHASE", class: "purchase-button" %>
    <% end %>
  <% end %> --%>
</div>

lib/sneakers23_web/controllers/checkout/checkout_html/success.html.heex
<div class="checkout-container">
  <h2>Order Complete!</h2>

  <p>
    Nice, your order is complete. If we stored orders, we could show you what you
    purchased here. Your cart has been cleared.
  </p>

  <.link href={~p"/"}>Go Home</.link>
</div>

<script type="text/javascript">
  delete localStorage.storedCart
</script>